#!/live/bin/sh

### BEGIN INIT INFO
# Provides:          live-bootsave
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description:
# Description:       save live boot options
### END INIT INFO

export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/live/bin

. /live/lib/live-init-utils.sh
start_init_logging


main() {
    case $1 in
        start) do_start                      ;;
         stop)                               ;;
            *) echo "Usage: $0 {start|stop}" ;;
    esac
    exit 0
}

do_start() {

    : ${CMDLINE:=$(cat /live/config/proc-cmdline /live/config/cmdline)}
    local gfx_cmd boot_save  vga_cmd  vga_ask
    for param in $CMDLINE; do
        local value=${param#*=}
        case $param in
            gfxsave=*) gfx_cmd=$value      ;;
                vga=*) vga_cmd=$value      ;;
              gfxsave) gfx_cmd=both        ;;
             bootsave) boot_save=true      ;;
        esac
    done

    case $vga_cmd in
        ask+save) gfx_cmd=both ; vga_ask=true ;;
             ask)                vga_ask=true ;;
    esac

    echo_script "Possibly saving boot parameters" $0
    get_real_vga_code "$vga_ask" "$gfx_cmd"

    [ -n "$gfx_cmd"   ] && do_gfxsave
    [ -n "$boot_save" ] && do_boot_save
}

do_gfxsave() {

    export CMDLINE
    export GFX_LOG_FILE=/var/log/live/gfxsave.log

    . $INITRD_OUT
    local dir=$BIOS_MP/boot
    test -d $dir || dir=$BOOT_MP/boot
    test -d $dir || return

    local dev=$(df -P $dir | tail -n1 | cut -d" " -f1)
    mount -o remount,rw $dev

    local script=/live/bin/gfxsave

    if ! [ -e /live/config/remasterable ]; then
        if [ -e /live/config/db+ ]; then
            local tdir=/live/test
            mkdir -p $tdir
            echo_live "Use $tdir to test %s" $(pquote $script)
            cp -r $dir/syslinux $tdir
            dir=$tdir
        else
            echo_live "Can't update %s on read-only boot media" "$(pquote gfxboot)"
            return
        fi
    fi

    $script $dir $gfx_cmd
}

do_boot_save() {
    . /live/config/initrd.out

    if [ "$BOOT_FSTYPE" = vfat ]; then
        grub2-save $BOOT_MP
    fi

    local uuid dir uuid_file file=esp-uuid
    for dir in $SQFILE_DIR $BOOT_MP; do
        test -r $dir/$file || continue
        uuid_file=$dir/$file
    done
    test -r $uuid_file || return
    read uuid 2>/dev/null <$uuid_file
    [ ${#uuid} -gt 0 ] || return

    local esp_mp=/live/esp
    mkdir -p $esp_mp
    mount --uuid $uuid $esp_mp
    mountpoint -q $esp_mp || return
    grub2-save $esp_mp
    sync
    umount $esp_mp
}

#------------------------------------------------------------------------------
#
#------------------------------------------------------------------------------
get_real_vga_code() {
    local vga_ask=$1  gfx_save=$2
    local hwinfo=/usr/sbin/hwinfo
    test -x $hwinfo    || return
    [ -n "$vga_ask" ]  || return
    [ -n "$gfx_save" ] || return

    echo_live "Probing to find selected vga code.  Please be patient ..."
    local vga_hex=$($hwinfo --vbe | sed -n "s/^\s*Current VESA Mode:\s*//p")
    if [ -z "$vga_hex" ]; then
        echo_live "No vga code was found!"
        return
    fi
    echo_live "Found hex code %s" "$(pquote $vga_hex)"
    local vga_dec=$(($vga_hex % 0x1000 + 0x200))
    echo_live "Using boot parameters %s" "$(pquote vga=$vga_dec)"
    local p_cmdline=/live/config/proc-cmdline
    sed -r "s/(^| )(vga=)[^ ]*/\1\2$vga_dec/" $p_cmdline > $p_cmdline.2
    CMDLINE=$(cat $p_cmdline.2 /live/config/cmdline 2>/dev/null)
}

main "$@" 2>&1 | tee -a $INIT_LOG_FILE

exit 0
